!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0
    t: 0
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1.1}
      rotations: [0]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 36, y: 0, z: 36}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
