!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 0
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1.1}
      rotations: [0]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 10, y: 0, z: 10}
      - !Vector3 {x: 15, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
      - !Vector3 {x: 2, y: 2, z: 2}
