!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0.5
    t: 500
    items:
    - !Item
      name: WallTransparent
      positions:
      - !Vector3 {x: 13.3, y: 0, z: 33}
      - !Vector3 {x: 26.6, y: 0, z: 33}
      - !Vector3 {x: 8, y: 0, z: 36}
      - !Vector3 {x: 20, y: 0, z: 36}
      - !Vector3 {x: 33.4, y: 0, z: 36}
      sizes:
      - !Vector3 {x: 14, y: 4, z: 1}
      - !Vector3 {x: 14, y: 4, z: 1}
      - !Vector3 {x: 1, y: 4, z: 3}
      - !Vector3 {x: 1, y: 4, z: 3}
      - !Vector3 {x: 1, y: 4, z: 3}
      rotations: [90, 90, 90, 90, 90]
      colors:
      - !RGB {r: 153, g: 153, b: 153} #color parameter
      - !RGB {r: 153, g: 153, b: 153} #color parameter
      - !RGB {r: 153, g: 153, b: 153} #color parameter
      - !RGB {r: 153, g: 153, b: 153} #color parameter
      - !RGB {r: 153, g: 153, b: 153} #color parameter

      
      
     # - !Vector3 {x: 6.6, y: 0, z: 32}
     # - !Vector3 {x: 20, y: 0, z: 32}
     # - !Vector3 {x: 33.3, y: 0, z: 32}
      
      
      
     # 
     # 
     # 
      
      
      
     # 
     # 
     # 
      
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 8, y: 10, z: 38}
     # - !Vector3 {x: 20, y: 7, z: 38}
     # - !Vector3 {x: 33.4, y: 7, z: 38}
      sizes:
      - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
     # - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
     # - !Vector3 {x: 1.5, y: 1.5, z: 1.5} #Goal Size
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 5}
      rotations: [0]

