!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0 #End
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [355]
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: 3, y: 0, z: 10}
      rotations: [90]
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}




