!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -0.1 #End.9 #End
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 30, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}



    blackouts: [-15]
