!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 2.9 #End
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [355]
    - !Item
      name: GoodGoalMulti
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4}





    blackouts: [-15]
