!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 3 #End
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [5]
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: 37, y: 0, z: 30}
      rotations: [270]
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4}




