!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: -0.5
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0]
    - !Item
      name: GoodGoalBounce
      positions:
      - !Vector3 {x: 37, y: 0, z: 20}
      rotations: [270]
      sizes:
      - !Vector3 {x: 0.5, y: 0.5, z: 0.5}

