!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 1
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [5]
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 10, y: 0, z: 20}
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}



