!ArenaConfig
arenas:
  -1: !Arena
    pass_mark: 0 #total score to pass
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 20, y: 0, z: 1}
      rotations: [0] #Agent rotation
    - !Item
      name: DeathZone
      positions:
      - !Vector3 {x: 20, y: 0, z: 15} # Lava Position
      rotations: [0] # Lava Rotation
      sizes:
      - !Vector3 {x: 7, y: 0.1, z: 1} # Lava Size
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 20} #GoodGoal Position
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4} #GoodGoal Size


    blackouts: [-15]
